In [ ]:
import joblib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, FunctionTransformer

# I- Import des données

In [ ]:
df = pd.read_csv("billets_production.csv", sep=",")
df.head()

   diagonal  height_left  height_right  margin_low  margin_up  length   id
0    171.76       104.01        103.54        5.21       3.30  111.42  A_1
1    171.87       104.17        104.13        6.00       3.31  112.09  A_2
2    172.00       104.58        104.29        4.99       3.39  111.57  A_3
3    172.49       104.55        104.34        4.44       3.03  113.20  A_4
4    171.65       103.63        103.56        3.77       3.16  113.33  A_5

# II- Préparation des données

In [ ]:
# Garder l'identifiant à part
ids = df["id"]
ids

0    A_1
1    A_2
2    A_3
3    A_4
4    A_5
Name: id, dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   diagonal      5 non-null      float64
 1   height_left   5 non-null      float64
 2   height_right  5 non-null      float64
 3   margin_low    5 non-null      float64
 4   margin_up     5 non-null      float64
 5   length        5 non-null      float64
 6   id            5 non-null      object
dtypes: float64(6), object(1)
memory usage: 412.0+ bytes

# III- Création de variables

In [ ]:
#L'aire
df["Area"] = round(df["length"] * ((df["height_right"] + df["height_left"])/2),2)

In [ ]:
#Différence des tailles
df["diff_height"] = abs(round(df["height_right"] - df["height_left"],2))

In [ ]:
# Différence des marges
df["diff_margin"] = abs(round(df["margin_up"] - df["margin_low"],2))

In [ ]:
#Somme des marges
df["sum_margin"] = round(df["margin_up"] + df["margin_low"],2)

In [ ]:
# Charger modèle
modele_charge = joblib.load("modele_final.joblib")

# Variables
X = df.drop(columns=["id"]) # Enlever id des variables utilisées par le modèle


# Prédictions
predictions = modele_charge.predict(X)
probas = modele_charge.predict_proba(X)[:, 1]

resultats = pd.DataFrame({
    "id": ids,
    "prediction": predictions,
    "probabilite_faux": probas,
    "resultat": ["FAUX ❌" if p == 1 else "VRAI ✅" for p in predictions]
})

print(resultats)

    id  prediction  probabilite_faux resultat
0  A_1           1          0.999610   FAUX ❌
1  A_2           1          0.999964   FAUX ❌
2  A_3           1          0.999910   FAUX ❌
3  A_4           0          0.015681   VRAI ✅
4  A_5           0          0.000071   VRAI ✅